[FEAT] 회고 목록 조회, 특정 타입 피드백 조회 api 구현
hwiwonK/MacC-Team-Maddori.Apple-Server pull request #30
Opened 2022-11-06 13:53 UTC by unanchoi

## 🌁 Background

- 나의 회고에서, 현재 팀에서 진행했던 회고 목록 조회 API를 구현했습니다.
- 회고 모음집에서 유저가 받은 특정 타입의 피드백 정보를 조회하는 API를 구현했습니다.
## 👩‍💻 Contents

- [x] 현재 팀에서 진행했던 회고 목록 가져오기
- [x] 특정 회고에서 유저가 받은 특정 타입의 피드백 정보 모두 가져오기
- [] 현재 팀의 최근 회고에서 유저가 받은 특정 타입의 피드백 정보 모두 가져오기

## ✅ Testing

Postman을 이용하여, API Test

- 현재 팀에서 진행했던 회고 목록 가져오기
URI : GET /teams/1/reflections

- 특정 회고에서 유저가 받은 특정 타입의 피드백 정보 모두 가져오기
URI : GET /teams/1/reflections/1/feedbacks/?type=Stop

## 📱 Screenshot

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/81692211/200174320-d3d5542b-b36e-4626-8b4e-cc92a8e0ba5c.png">

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/81692211/200174686-db0b2827-d187-4d82-bc6f-f74230ecc224.png">

## 📝 Review Note

## 📣 Related Issue

- close #29 

## 📬 Reference

2022-11-07 02:44 UTC, hwiwonK commented on Maddori.Apple-Server/routes/reflections/reflections.js
> +            where:{
p3;
사소한거지만.. 여기 { 앞에 띄어쓰기 부탁드립니다!

2022-11-07 02:45 UTC, hwiwonK commented on Maddori.Apple-Server/routes/reflections/reflections.js
> +        // 팀의 현재 회고의 reflection_name,date, status
p3;
여기도 사소한거지만.. 주석 date 앞에 띄어쓰기가 업어진 것 같은데 다시 추가 부탁드려요!

2022-11-07 02:46 UTC, hwiwonK commented on Maddori.Apple-Server/routes/reflections/index.js
> +router.get("/", getPastReflectionList);
p3;
endpoint는 다 작은따옴표(')로 묶어줬었어서, 여기도 그렇게 통일하는게 좋을 것 같네요!

2022-11-07 02:54 UTC, hwiwonK commented on Maddori.Apple-Server/routes/feedbacks/feedbacks.js
> +        })
p1;
현재 이 API가 쓰이는 화면은 아래와 같은 화면입니다!
<img width="287" alt="image" src="https://user-images.githubusercontent.com/67336936/200216299-72ba9143-87d7-40cc-aa5f-00f6fbd70bcd.png">

그래서 현재 보내주시는 id, type, keyword, content, start_content, from_id, to_id, team_id, reflection_id 외에도, **reflection_name**, 보내는 사람의 **username** 필드가 필요합니다.
sequelize의 include 를 활용해 user 테이블의 username, reflection 테이블의 reflection_name을 함께 가져오는 작업을 추가해주시면 좋을 것 같아요!

2022-11-07 02:58 UTC, hwiwonK commented on Maddori.Apple-Server/routes/feedbacks/feedbacks.js
> +        })
p4;
그리고 이렇게 배열 형식으로 response를 보내는 상황에서 저는 feedbacks : [ ~~ ] 식으로 그 배열이 무엇을 담고 있는 배열인지 명시해줬었는데, 로벗은 detail 에 바로 배열을 담으셨네요!
이 부분을 어떻게 통일하면 좋을지 의견 나누면 좋을 것 같아요. 전 response 데이터가 어떤 데이터인지 최대한 표현되었으면 좋겠어서 배열에 이름을 붙이고 싶었는데, 로벗은 어떻게 생각하시나요?

2022-11-07 03:00 UTC, hwiwonK requested changes
빠른 구현 정말 최고입니다.. 구현되어 있는 코드 스타일과 비슷하게 맞춰서 구현해주신 점 정말 감사합니다👍
코멘트 남긴 부분만 수정해주시면 approve하겠습니다!

2022-11-07 03:07 UTC, unanchoi commented on Maddori.Apple-Server/routes/feedbacks/feedbacks.js
> +        })
아하!!
detail : {
  feedbacks: [
     ~~
  ]
}
이렇게 표현하고 싶으신게 맞을까요?? 좋습니다!

2022-11-07 03:43 UTC, hwiwonK commented on Maddori.Apple-Server/routes/feedbacks/feedbacks.js
> +        })
네 맞습니다! 그럼 앞으로도 배열 보내는 상황에선 이렇게 배열 이름 명시하는걸로 할게요😊

2022-11-07 03:50 UTC, hwiwonK commented on Maddori.Apple-Server/routes/feedbacks/feedbacks.js
> +        return res.status(200).json({'success':true, 'message':'피드백 조회 성공','detail':feedbackData});
p3;
아 그리고 response 보낼 때도
```javascript
  res.status(201).json({
      success: true,
      message: '유저 로그인 성공',
      datail: createdUser
  });
```
이런식으로 convention 지켜서 보내는거 어떠신가요??

2022-11-07 03:56 UTC, unanchoi commented on Maddori.Apple-Server/routes/feedbacks/feedbacks.js
> +        })
추가했습니다!

2022-11-07 03:58 UTC, unanchoi commented on Maddori.Apple-Server/routes/feedbacks/feedbacks.js
> +        return res.status(200).json({'success':true, 'message':'피드백 조회 성공','detail':feedbackData});
아하 알겠습니다!!

2022-11-07 03:59 UTC, unanchoi commented on Maddori.Apple-Server/routes/feedbacks/feedbacks.js
> +        return res.status(200).json({'success':true, 'message':'피드백 조회 성공','detail':feedbackData});
수정해서 다시 push하겠습니다!

2022-11-08 11:14 UTC, hwiwonK approved these changes
코드 리뷰 반영하신거 확인했습니다!
코드 컨벤션 맞추기 번거로우셨을텐데 수고 많으셨습니다👍
다른 브랜치 파서 작업하실 때 꼭 디벨롭 풀 받아주시고, 아직 로벗님의 feedback 테이블에 is_favorite 필드가 남아있는 것 같아서 테이블 날린 후에 재 생성부탁드려요! 화이팅~~~💪

2022-11-08 11:55 UTC, merged